/* Lesson 48. "get" */
CREATE TABLE Person (
  id int PRIMARY KEY,
  name varchar(100),
  age int
);

/* We create sequence if we assign PRIMARY KEY-field id not with the Postgres default
   sequence approach */
CREATE SEQUENCE person_id_seq;

/** Standard PostgreSQL approach for sequences can be defined as:
   -- auto-generated definition
  **/
    create sequence person_id_seq;
    alter sequence person_id_seq owner to postgres;
    alter sequence person_id_seq owned by person.id;



INSERT INTO Person(id, name, age) VALUES(1, 'Test Person', 20);

SELECT * FROM Person;

/* Lesson 49. "save" */
DROP TABLE Person;

CREATE TABLE Person (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    age int
);

SELECT * FROM Person;