/* Lesson 48. "get" */
CREATE TABLE Person (
  id int PRIMARY KEY,
  name varchar(100),
  age int
);

/* We create sequence if we assign PRIMARY KEY-field id not with the Postgres default
   sequence approach */
CREATE SEQUENCE person_id_seq;

/** Standard PostgreSQL approach for sequences can be defined as:
   -- auto-generated definition
  **/
    create sequence person_id_seq;
    alter sequence person_id_seq owner to postgres;
    alter sequence person_id_seq owned by person.id;




SELECT * FROM Person;

/* Lesson 49. "save" */
DROP TABLE Person;

CREATE TABLE Person (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    age int
);

INSERT INTO Person(name, age) VALUES('Test Person 1', 20);
INSERT INTO Person(name, age) VALUES('Test Person 2', 30);
INSERT INTO Person(name, age) VALUES('Test Person 3', 40);
INSERT INTO Person(name, age) VALUES('Test Person 4', 50);


SELECT * FROM Person;

SELECT * FROM Person WHERE NAME LIKE '%2';